WebApplication5/Models/Guider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication5.Models
{
    public class Guider
    {
        [Key]
        [ForeignKey("ApplicationUser")]
        public string GuiderID { get; set; }

        [StringLength(256)]
        public string Image { get; set; }

        [StringLength(256)]
        public string ImageFullPath { get; set; }
        
        [StringLength(256)]
        public string Skype { get; set; }

        [StringLength(2000)]
        public string AboutMe { get; set; }

        [StringLength(256)]
        public string AdressOfTaking { get; set; }

        [StringLength(50)]
        public string Country { get; set; }

        [StringLength(50)]
        public string City { get; set; }

        [StringLength(100)]
        public string Adress { get; set; }

        [StringLength(256)]
        public string IBAN { get; set; }

        [StringLength(256)]
        public string Passport { get; set; }

        [StringLength(256)]
        public string DocumentPDF { get; set; }

        [DataType(DataType.Currency)]
        public decimal ChargePerHour { get; set; }

        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public bool IsAccepted { get; set; }

        [ForeignKey("CancellationPolicy")]
        public int? CancellationPolicyID { get; set; }

        [ForeignKey("Premium")]
        public int? PremiumID { get; set; }

        public virtual Premium Premium { get; set; }
        public virtual CancellationPolicy CancellationPolicy { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }

        public virtual ICollection<UnavailableDate> UnavailableDates { get; set; }
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<TravellerToGuiderRate> TravellerToGuiderRates { get; set; }
        public virtual ICollection<GuiderToTravellerBan> GuiderToTravellerBans { get; set; }
        public virtual ICollection<Certificate> Certificates { get; set; }
        public virtual ICollection<GuiderLanguageSkill> GuiderLanguageSkills { get; set; }
        public virtual ICollection<TravellerToGuiderFavourite> TravellerToGuiderFavourite { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
    }
}

WebApplication5/Controllers/GuiderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication5.Models;
using System.Threading.Tasks;
using Newtonsoft.Json;
using WebApplication5.Services;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using PagedList;
using WebApplication5.ViewModels;

namespace WebApplication5.Controllers
{
    public class GuiderController : Controller
    {
        private GuiderService guiderService = new GuiderService();

        // GET: Guider
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Guider/ShowGuiders
        [HttpGet]
        public ActionResult ShowGuiders(string cityLat, string cityLng, int? page)
        {
            ViewBag.CurrentLat = cityLat;
            ViewBag.CurrentLng = cityLng;

            var nearbyGuiders = guiderService.ShowGuiders(cityLat, cityLng, page);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("ShowGuiders", nearbyGuiders.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Guider/GetGuiderProfile
        [HttpGet] 
        public ActionResult GetGuiderProfile(string guiderId)
        {
            PublicProfileGuiderViewModel publicProfileGuider = new PublicProfileGuiderViewModel();
            List<TravellerToGuiderRate> rates = new List<TravellerToGuiderRate>();
            if (guiderId == null)
            {
                // return View("Error");
            }

            try
            {
                publicProfileGuider.Guider = guiderService.GetGuider(guiderId);
                rates = guiderService.GetRatesOfSpecificGuider(guiderId);
                int sum = 0;
                if(rates.Count != 0)
                {
                    foreach (var item in rates)
                    {
                        sum += item.Rate;
                    }
                    publicProfileGuider.OverralRating = sum / rates.Count;
                    publicProfileGuider.TravellerToGuiderRates = rates;
                }
                else
                {
                    publicProfileGuider.OverralRating = 0;
                }
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
            return View("GetGuiderProfile", publicProfileGuider);
        }

        ////
        //// POST: Add Guider into favourite list of current user
        //[HttpPost]
        //public JsonResult SetFavouriteGuider(string guiderId, string currentUserId)
        //{

        //    return Json();
        //}
    }
}

WebApplication5/Views/Guider/GuiderProfileCalendar.cshtml
@{
    Layout = null;
}


<div id="calendar-body">
        <div id="input" class="article">
            <h3><span>Request a guid :)</span></h3>
            <h6><i>Check in ---> Check out</i></h6>
            <input type="text" class="input-calendar" />
            <div class="box"></div>
            <div class="tag price">$ @Model</div>
            <p></p>
        </div>
</div>

WebApplication5/Views/Guider/ShowGuiderPartial.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}

<div class="search-box-wrapper">
    <div class="search-box-inner">
        <div class="container">
            <div class="search-box map">
                <ul class="nav nav-pills">
                    <li class="active"><a href="#search-form-sale" data-toggle="tab">Sale</a></li>
                </ul>
                <hr>
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="search-form-sale">
                        <a class="advanced-search-toggle" data-toggle="collapse" data-parent="#accordion" href="#advanced-search-sale">Advanced Sale Search <i class="fa fa-plus"></i></a>
                        @*<form role="form" id="form-map-sale" class="form-map form-search clearfix has-dark-background"></form>*@<!-- /#form-map-sale -->
                        @using (Html.BeginForm("ShowGuiders", "Guider", FormMethod.Get, new { role = "form", @id = "form-sidebar", @class = "form-search" }))
                        {
                            <div id="advanced-search-sale" class="panel-collapse collapse">
                                <div class="advanced-search">
                                    <header><h3>Property Features</h3></header>
                                    <ul class="submit-features">
                                        <li><div class="checkbox"><label><input type="checkbox">Air conditioning</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Bedding</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Heating</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Internet</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Microwave</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Smoking allowed</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Use of pool</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Toaster</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Coffee pot</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Cable TV</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Parquet</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Roof terrace</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Terrace</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Balcony</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Iron</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Hi-Fi</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Beach</label></div></li>
                                        <li><div class="checkbox"><label><input type="checkbox">Garage</label></div></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-2 col-sm-4">

                                </div>

                                <div class="col-md-2 col-sm-4">

                                </div>
                                <div class="col-md-2 col-sm-4">
                                    <div class="form-group">
                                        <!-- id="search-box-property-id" changed with id="autocompleted" -->
                                        <div class="form-group" id="locationField">
                                            <input id="searchTextField" type="text" size="50" placeholder="Enter a location" autocomplete="on" />
                                            <input type="text" id="city2" name="city2" />
                                            <input type="text" id="cityLat" name="cityLat" />
                                            <input type="text" id="cityLng" name="cityLng" />
                                        </div>

                                    </div><!-- /.form-group -->

                                </div>
                                @*<div class="col-md-2 col-sm-4">
                                        <div class="form-group">
                                            <select name="form-sale-price">
                                                <option value="">Price</option>
                                                <option value="1">$10,000 +</option>
                                                <option value="2">$50,000 +</option>
                                                <option value="3">$100,000 +</option>
                                                <option value="4">$500,000 +</option>
                                            </select>
                                        </div>
                                    </div>*@
                                <div class="col-md-2 col-sm-4">
                                    <div class="form-group">
                                        @*<button id="search" type="submit" class="btn btn-default">Search Sale</button>*@
                                        <input type="submit" class="btn btn-default" value="Search" />
                                    </div><!-- /.form-group -->
                                </div>
                            </div>
                        }
                    </div><!-- /#search-form-rent -->
                </div><!-- /.tab-content -->
            </div><!-- /.search-box -->
        </div><!-- /.container -->
    </div><!-- /.search-box-inner -->
    <div class="background-image"><img class="opacity-20" src="~/assets/img/searchbox-bg.jpg"></div>
</div>
<!--[if gt IE 8]>
    <script type="text/javascript" src="assets/js/ie.js"></script>
    <![endif]-->
<!--
<script>
    _latitude = 48.87;
    _longitude = 2.29;
    createHomepageGoogleMap(_latitude,_longitude);
    $(window).load(function(){
        initializeOwl(false);
    });
</script>
-->
@*<script type="text/javascript">
    function initialize() {
        var input = document.getElementById('searchTextField');
        var autocomplete = new google.maps.places.Autocomplete(input);
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
            var place = autocomplete.getPlace();
            document.getElementById('city2').value = place.name;
            document.getElementById('cityLat').value = place.geometry.location.lat();
            document.getElementById('cityLng').value = place.geometry.location.lng();
            //alert("This function is working!");
            //alert(place.name);
            // alert(place.address_components[0].long_name);

        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>*@

<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyC34PVHithrgKTqdV4LEid9Le_-IFrZ150&libraries=places" type="text/javascript"></script>
<script type="text/javascript">
    function initialize() {
        var input = document.getElementById('searchTextField');
        var autocomplete = new google.maps.places.Autocomplete(input);
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
            var place = autocomplete.getPlace();
            document.getElementById('city2').value = place.name;
            document.getElementById('cityLat').value = place.geometry.location.lat();
            document.getElementById('cityLng').value = place.geometry.location.lng();
            //alert("This function is working!");
            //alert(place.name);
            // alert(place.address_components[0].long_name);

        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

WebApplication5/Views/Guider/ShowGuiders.cshtml
@model PagedList.IPagedList<WebApplication5.Models.Guider>
@using PagedList.Mvc;
@{
    ViewBag.Title = "ShowGuiders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("~/Views/Guider/ShowGuiderPartial.cshtml")
<section id="new-properties" class="block">
    <div class="container">
        <div class="row">
            <!-- Results -->
            <div class="col-md-9 col-sm-9">
                <section id="results">
                    <header><h1>Properties Listing</h1></header>
                    <section id="search-filter">
                        <figure>
                            <h3><i class="fa fa-search"></i>Search Results:</h3>
                            <span class="search-count">@Model.Count</span>
                            <div class="sorting">
                                <div class="form-group">
                                    <select name="sorting">
                                        <option value="">Sort By</option>
                                        <option value="1">Lowest price first</option>
                                        <option value="2">Highest price first</option>
                                        <option value="3">Date added</option>
                                    </select>
                                </div><!-- /.form-group -->
                            </div>
                        </figure>
                    </section>
                    <section id="properties" class="display-lines">
                        @foreach (var item in Model)
                        {
                            <div class="property">
                                <figure class="tag status">8.4/10</figure> <!-- Score -->
                                <div class="property-image">
                                    <figure class="ribbon">Favourite</figure> <!-- Favourite *****-->
                                    <a href="property-detail.html">
                                        @if (item.Image != null)
                                        {
                                            <img alt="" src="@Url.Content(item.Image)"> <!-- Image -->
                                        }
                                        else
                                        {
                                            <img alt="" class="image" src="~/assets/img/agent-01.jpg" /> <!-- Default user image-->
                                        }
                                    </a>
                                </div>
                                <div class="info">
                                    <header>
                                        <a href="property-detail.html"><h3>@item.ApplicationUser.Name @item.ApplicationUser.Lastname</h3></a> <!-- Name of guider -->
                                        <figure>Ikoniou 4, Stayroupoli</figure> <!-- Adress of guider that will meet you -->
                                    </header>
                                    <div class="tag price">$ 10 / hour</div> <!-- Cost -->
                                    <aside>
                                        <p>
                                            @item.AboutMe
                                        </p>
                                        <dl style="visibility: hidden;">
                                            <dt>Status:</dt>
                                            <dd>Sale</dd>
                                            <dt>Area:</dt>
                                            <dd>860 m<sup>2</sup></dd>
                                            <dt>Beds:</dt>
                                            <dd>3</dd>
                                            <dt>Baths:</dt>
                                            <dd>2</dd>
                                        </dl>
                                    </aside>
                                    <a href="property-detail.html" class="link-arrow">Read More</a>
                                    @Html.ActionLink("Read More", "GetGuiderProfile", new { guiderId = item.GuiderID }, new { @class = "link-arrow" })
                                </div>
                            </div><!-- /.property -->
                        }
                        <!-- Pagination -->
                        <div class="center">
                            <ul class="pagination">
                                @Html.PagedListPager(Model, page => Url.Action("ShowGuiders", new { page, cityLat = ViewBag.CurrentLat, cityLng = ViewBag.CurrentLng }))
                            </ul><!-- /.pagination-->
                        </div><!-- /.center-->
                    </section><!-- /#properties-->
                </section><!-- /#results -->
            </div><!-- /.col-md-9 -->
            <!-- end Results -->
            <!-- sidebar -->
            <div class="col-md-3 col-sm-3">
                <section id="sidebar">
                    <aside id="edit-search">
                        <header><h3>Search Properties</h3></header>
                        <form role="form" id="form-sidebar" class="form-search" action="properties-listing.html">
                            <div class="form-group">
                                <select name="type">
                                    <option value="">Status</option>
                                    <option value="1">Rent</option>
                                    <option value="2">Sale</option>
                                </select>
                            </div><!-- /.form-group -->
                            <div class="form-group">
                                <select name="country">
                                    <option value="">Country</option>
                                    <option value="1">France</option>
                                    <option value="2">Great Britain</option>
                                    <option value="3">Spain</option>
                                    <option value="4">Russia</option>
                                    <option value="5">United States</option>
                                </select>
                            </div><!-- /.form-group -->
                            <div class="form-group">
                                <select name="city">
                                    <option value="">City</option>
                                    <option value="1">New York</option>
                                    <option value="2">Los Angeles</option>
                                    <option value="3">Chicago</option>
                                    <option value="4">Houston</option>
                                    <option value="5">Philadelphia</option>
                                </select>
                            </div><!-- /.form-group -->
                            <div class="form-group">
                                <select name="district">
                                    <option value="">District</option>
                                    <option value="1">Manhattan</option>
                                    <option value="2">The Bronx</option>
                                    <option value="3">Brooklyn</option>
                                    <option value="4">Queens</option>
                                    <option value="5">Staten Island</option>
                                </select>
                            </div><!-- /.form-group -->
                            <div class="form-group">
                                <select name="property-type">
                                    <option value="">Property Type</option>
                                    <option value="1">Apartment</option>
                                    <option value="2">Condominium</option>
                                    <option value="3">Cottage</option>
                                    <option value="4">Flat</option>
                                    <option value="5">House</option>
                                </select>
                            </div><!-- /.form-group -->
                            <div class="form-group">
                                <div class="price-range">
                                    <input id="price-input" type="text" name="price" value="1000;299000">
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-default">Search Now</button>
                            </div><!-- /.form-group -->
                        </form><!-- /#form-map -->
                    </aside><!-- /#edit-search -->
                    <aside id="featured-properties">
                        <header><h3>Featured Properties</h3></header>
                        <div class="property small">
                            <a href="property-detail.html">
                                <div class="property-image">
                                    <img alt="" src="assets/img/properties/property-06.jpg">
                                </div>
                            </a>
                            <div class="info">
                                <a href="property-detail.html"><h4>2186 Rinehart Road</h4></a>
                                <figure>Doral, FL 33178 </figure>
                                <div class="tag price">$ 72,000</div>
                            </div>
                        </div><!-- /.property -->
                        <div class="property small">
                            <a href="property-detail.html">
                                <div class="property-image">
                                    <img alt="" src="assets/img/properties/property-09.jpg">
                                </div>
                            </a>
                            <div class="info">
                                <a href="property-detail.html"><h4>2479 Murphy Court</h4></a>
                                <figure>Minneapolis, MN 55402</figure>
                                <div class="tag price">$ 36,000</div>
                            </div>
                        </div><!-- /.property -->
                        <div class="property small">
                            <a href="property-detail.html">
                                <div class="property-image">
                                    <img alt="" src="assets/img/properties/property-03.jpg">
                                </div>
                            </a>
                            <div class="info">
                                <a href="property-detail.html"><h4>1949 Tennessee Avenue</h4></a>
                                <figure>Minneapolis, MN 55402</figure>
                                <div class="tag price">$ 128,600</div>
                            </div>
                        </div><!-- /.property -->
                    </aside><!-- /#featured-properties -->
                    <aside id="our-guides">
                        <header><h3>Our Guides</h3></header>
                        <a href="#" class="universal-button">
                            <figure class="fa fa-home"></figure>
                            <span>Buying Guide</span>
                            <span class="arrow fa fa-angle-right"></span>
                        </a><!-- /.universal-button -->
                        <a href="#" class="universal-button">
                            <figure class="fa fa-umbrella"></figure>
                            <span>Right Insurance for You</span>
                            <span class="arrow fa fa-angle-right"></span>
                        </a><!-- /.universal-button -->
                    </aside><!-- /#our-guide -->
                </section><!-- /#sidebar -->
            </div><!-- /.col-md-3 -->
            <!-- end Sidebar -->
        </div><!-- /.row -->
    </div><!-- /.container -->
    <!-- /.container -->
</section><!-- /#new-properties-->